### ISSUE TITLE
`@link to page` not working

### ISSUE THREAD

**Issue by omarcostahamido** [aidistan/notion-custom-domain#1]
Hi @aidistan 
`@link to page` links will load the original notion domain, not our custom domain. 
Haven't been able to fix it myself, despite my efforts.
Can you help me to figure this one out?

**Comment by aidistan** [comment]
Hi @omarcostahamido.

It seems `@link to page` uses absolute paths instead of relative ones in order to inter-link between different notion workspaces.

A simple way to fix it is to watch DOM mutations of `a.notion-page-mention-token` nodes and substitute the custom domain for your notion domain if the `href` attribute starts from that.

Hope it helps :)
